version: '3'

services:
  reverseproxy:
    image: nginx:1.23
    # https://hub.docker.com/_/nginx?tab=tags
    #build:
    #  context: .
    #  dockerfile: nginx/nginx.Dockerfile
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/felipeschirmann.dev.br.pem:/etc/ssl/certs/site.crt
      - ./ssl/felipeschirmann.dev.br.key:/etc/ssl/private/site.dec.key
      - ./ssl/cloudflare.crt:/etc/ssl/certs/cloudflare.crt
  bds06:
    depends_on:
      - reverseproxy
    image: "felipeschirmann/bds06:latest"
    ports:
      - 8084:8080
    restart: always
  ds-vendas-docker:
    depends_on:
      - reverseproxy
    image: "felipeschirmann/ds-vendas-docker:latest"
    ports:
      - 8082:8080
    restart: always
  ds-movie-docker:
    depends_on:
      - reverseproxy
    image: "felipeschirmann/ds-movie-docker:latest"
    ports:
      - 8080:8080
    restart: always

#  docker run -p 8080:8080 -d felipeschirmann/ds-movie-docker
#  docker run -p 8082:8080 -d felipeschirmann/ds-vendas-docker
#

#### refs
# https://gist.github.com/dahlsailrunner/679e6dec5fd769f30bce90447ae80081