---
- name: Configure server Database
  hosts: db

  user: opc
  become: true

  vars_files:
    - vars/main.yml

  tasks:
  - name: What is my inventory_hostname
    debug: var={{inventory_hostname}}
      
  - name: What is my ansible_hostname
    debug: var={{ansible_hostname}}

  - name: Creat app dir
    file:
      path: /opt/postgres
      state: directory
      owner: opc
      group: opc

  - name: Copy docker-compose
    template:
      src: postgres/docker-compose.yml
      dest: /opt/postgres/docker-compose.yml

  roles:
    - configuration-default-so